### ISSUE TITLE
Failed to unmarshal rdjson on version 1.20.0

### ISSUE THREAD

**Issue by taltcher** [reviewdog/action-stylelint#112]
After upgrading to version 1.20.0 we have started to receive:
```
reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 2:1): unexpected token
```

**Comment by haya14busa** [comment]
Can you work on it? @bert-mccutchen

**Comment by taltcher** [comment]
Hi @bert-mccutchen -
This is the full error that I'm seen:

```
  TypeError: Cannot read properties of undefined (reading 'CssSyntaxError')
      at /home/runner/work/_actions/reviewdog/action-stylelint/v1/stylelint-formatter-rdjson/index.js:36:40
      at Array.forEach (<anonymous>)
      at /home/runner/work/_actions/reviewdog/action-stylelint/v1/stylelint-formatter-rdjson/index.js:17:21
      at Array.forEach (<anonymous>)
      at module.exports (/home/runner/work/_actions/reviewdog/action-stylelint/v1/stylelint-formatter-rdjson/index.js:14:35)
      at prepareReturnValue (/home/runner/work/frontend/frontend/node_modules/stylelint/lib/prepareReturnValue.js:51:23)
      at standalone (/home/runner/work/frontend/frontend/node_modules/stylelint/lib/standalone.js:281:17)
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 2:1): unexpected token 
Error: Process completed with exit code 1.
```

Which logs do you want me to find?

**Comment by bert-mccutchen** [comment]
Ahh, that's actually perfect, thank you.

**Comment by th0th** [comment]
Hey, I am not sure if it is the same problem, but I didn't want to create a new issue in case it is.

I am getting this in the Github action log (with debug enabled):

```
##[debug]Evaluating condition for step: 'Run stylelint'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run stylelint
##[debug]Loading inputs
##[debug]Evaluating: secrets.GITHUB_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'GITHUB_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run reviewdog/action-stylelint@v1.[2](https://github.com/th0th/repo/actions/runs/x/job/x#step:10:2)0.1
##[debug]Evaluating: inputs.github_token
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'github_token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: inputs.level
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'level'
##[debug]=> 'error'
##[debug]Result: 'error'
##[debug]Evaluating: inputs.fail_on_error
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'fail_on_error'
##[debug]=> 'true'
##[debug]Result: 'true'
##[debug]Evaluating: inputs.filter_mode
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'filter_mode'
##[debug]=> 'nofilter'
##[debug]Result: 'nofilter'
##[debug]Evaluating: inputs.name
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'name'
##[debug]=> 'stylelint'
##[debug]Result: 'stylelint'
##[debug]Evaluating: inputs.packages
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'packages'
##[debug]=> ''
##[debug]Result: ''
##[debug]Evaluating: inputs.reporter
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'reporter'
##[debug]=> 'github-pr-review'
##[debug]Result: 'github-pr-review'
##[debug]Evaluating: inputs.stylelint_input
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'stylelint_input'
##[debug]=> '**/*.scss'
##[debug]Result: '**/*.scss'
##[debug]Evaluating: inputs.stylelint_config
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'stylelint_config'
##[debug]=> ''
##[debug]Result: ''
##[debug]Evaluating: inputs.stylelint_ignore
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'stylelint_ignore'
##[debug]=> ''
##[debug]Result: ''
##[debug]Evaluating: inputs.workdir
##[debug]Evaluating Index:
##[debug]..Evaluating inputs:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'workdir'
##[debug]=> 'frontend'
##[debug]Result: 'frontend'
##[debug]Evaluating condition for step: 'run'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: run
##[debug]Loading inputs
##[debug]Loading env
Run $GITHUB_ACTION_PATH/script.sh
##[debug]/usr/bin/bash --noprofile --norc -e -o pipefail /home/runner/work/_temp/4f52ba87-8411-4590-aa4e-6a8bb5a[3](https://github.com/th0th/repo/actions/runs/repo/job/x#step:10:3)e7b9.sh
::group:: Installing reviewdog 🐶 ... https://github.com/reviewdog/reviewdog
 Installing reviewdog 🐶 ... https://github.com/reviewdog/reviewdog
1[6](https://github.com/th0th/repo/actions/runs/x/job/x#step:10:6).2.1
stylelint version: [16](https://github.com/th0th/repo/actions/runs/x/job/x#step:10:16).2.1
::group:: Running stylelint with reviewdog 🐶 ...
 Running stylelint with reviewdog 🐶 ...
  {"source":{"name":"stylelint","url":"https://stylelint.io/"},"diagnostics":[]}reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 2:1): unexpected token 
  ::endgroup::
Error: Process completed with exit code 1.
##[debug]Finished: run
##[debug]Finishing: Run stylelint
```

**Comment by bert-mccutchen** [comment]
@th0th is that pre-1.20.1 release or post-1.20.1 release?

**Comment by th0th** [comment]
I get this with `uses: reviewdog/action-stylelint@v1.20.1`.

**Comment by bert-mccutchen** [comment]
@th0th you don't by any change happen to be using Stylelint 16, eh?

**Comment by taltcher** [comment]
Hi @haya14busa @bert-mccutchen - seems like there is still an issue... Tried to run the action with the updated version - and receive the next error:
```
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:4259): invalid escape code "\\." in string
```
I don't see know any stackstrace... Just this error

**Comment by gjoremilevsk1** [comment]
Hi all, any progress or time estimate for a fix here? We're facing the same issue.
